# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("VK PLAYER")
        MainWindow.resize(512, 340)
        MainWindow.setMinimumSize(QtCore.QSize(512, 340))
        MainWindow.setMaximumSize(QtCore.QSize(512, 340))
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet("")
        self.tableWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(3, 3, 506, 261))
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setKerning(True)
        item.setFont(font)
        self.duration_slider = QtWidgets.QSlider(self.centralwidget)
        self.duration_slider.setGeometry(QtCore.QRect(3, 270, 506, 15))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.duration_slider.setFont(font)
        self.duration_slider.setAcceptDrops(False)
        self.duration_slider.setAutoFillBackground(True)
        self.duration_slider.setMaximum(240)
        self.duration_slider.setOrientation(QtCore.Qt.Horizontal)
        self.duration_slider.setInvertedAppearance(False)
        self.duration_slider.setInvertedControls(False)
        self.duration_slider.setObjectName("duration_slider")
        self.verticalSlider = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider.setGeometry(QtCore.QRect(490, 291, 22, 44))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.verticalSlider.setMaximum(100)
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(50, 296, 133, 14))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.title.setStyleSheet('color: #222222')
        self.artist = QtWidgets.QLabel(self.centralwidget)
        self.artist.setGeometry(QtCore.QRect(50, 313, 133, 14))
        self.artist.setStyleSheet('color: #222222;')
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.artist.setFont(font)
        self.artist.setObjectName("artist")
        self.ico = QtWidgets.QLabel(self.centralwidget)
        self.ico.setGeometry(QtCore.QRect(5, 292, 42, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ico.sizePolicy().hasHeightForWidth())
        self.ico.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(5)
        self.ico.setFont(font)
        self.ico.setStyleSheet("""border-radius: 25px;
        min-height: 42px;
        max-height: 42px;
        min-width: 42px;
        max-width: 42px;""")
        self.ico.setText("")
        self.ico.setTextFormat(QtCore.Qt.AutoText)
        self.ico.setScaledContents(True)
        self.ico.setAlignment(QtCore.Qt.AlignCenter)
        self.ico.setObjectName("ico")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 302, 471, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 5, 1, 1)
        self.play_pause = QtWidgets.QPushButton(self.layoutWidget)
        self.play_pause.setStyleSheet("")
        self.play_pause.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_pause.setIcon(icon)
        self.play_pause.setIconSize(QtCore.QSize(16, 16))
        self.play_pause.setObjectName("play_pause")
        self.gridLayout.addWidget(self.play_pause, 0, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/rewind.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setStyleSheet("")
        self.pushButton_4.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assets/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 0, 3, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_5.setStyleSheet("")
        self.pushButton_5.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("assets/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon3)
        self.pushButton_5.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_5.setObjectName("pushButton_5")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("assets/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(340, 302, 28, 24))
        self.pushButton_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_6.setStyleSheet("")
        self.pushButton_6.setIcon(icon4)
        self.pushButton_6.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_5, 0, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.column_phon = QtWidgets.QColumnView(self.centralwidget)
        self.column_phon.setGeometry(QtCore.QRect(3, 290, 506, 46))
        self.column_phon.setObjectName("column_phon")
        self.column_phon.raise_()
        self.tableWidget.raise_()
        self.duration_slider.raise_()
        self.title.raise_()
        self.artist.raise_()
        self.ico.raise_()
        self.verticalSlider.raise_()
        self.layoutWidget.raise_()
        self.pushButton_6.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VK Player"))
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.headerItem().setText(0, _translate("MainWindow", "Номер"))
        self.tableWidget.headerItem().setText(1, _translate("MainWindow", "Название"))
        self.tableWidget.headerItem().setText(2, _translate("MainWindow", "Исполнитель"))
        self.tableWidget.headerItem().setText(3, _translate("MainWindow", "Длительность"))
        self.tableWidget.setColumnWidth(0, 70)
        self.tableWidget.setColumnWidth(1, 170)
        self.tableWidget.setColumnWidth(2, 150)
        self.tableWidget.setColumnWidth(3, 10)
